### ISSUE TITLE
Make graphs look decent + mobile friendly

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-dashboard#1]

**Comment by johnoliver** [comment]
I think some of the sizing goes beyond mobile issues. even on desktop https://dash.adoptopenjdk.net/github.html looks very distorted:

![image](https://user-images.githubusercontent.com/1615532/47995673-fbbae280-e0ed-11e8-935d-1b9e35fcfdb6.png)

Also the page https://dash.adoptopenjdk.net/version.html?version=jdk8&tag=jdk8u192-b12 at certain resolutions appears to shake like crazy. I think what is happening is there is some auto scaling, where it continually resizes that causes the scroll bar to appear, it then resizes to account for the scroll bar, this removes the scroll bar...and repeat.
