### ISSUE TITLE
uBlock (ad blocker) blocks Homebrew stats

### ISSUE THREAD

**Issue by Maldivia** [AdoptOpenJDK/openjdk-dashboard#11]
If user has an ad blocker installed (tested with uBlock Origin in Chrome), that includes the EasyPrivacy filter list, then the Homebrew stats page will be blank, as the request to the json file contains the data will be blocked (the URL matches the filter `/api/analytics/*`).

Screenshot of the matched filter and blocked request from uBlock Origin:
![image](https://user-images.githubusercontent.com/1133537/55067854-269bd800-5089-11e9-8132-1bf8a660b656.png)

**Comment by gdams** [comment]
not sure what I can do to work around this? we depend on the API route provided by homebrew. Can you not create an exception?

**Comment by Maldivia** [comment]
I would assume most ad blockers have the possibility to do so (uBlock Origin does), but does the user know this, or that it's even the reason -- all they see is an empty page:
![image](https://user-images.githubusercontent.com/1133537/55150217-5d8af000-5154-11e9-92bb-585c57063022.png)

**Comment by gdams** [comment]
it's probably worth raising an issue at https://github.com/Homebrew/homebrew-core to discuss this further. Will close over here
