### ISSUE TITLE
Persist historical download stats for trend analysis

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-dashboard#16]
I would be nice to be able to draw graphs of download trends, eg.import data into excel etc...
To do this we'd obviously need to persist stats somewhere...

**Comment by karianna** [comment]
#14

**Comment by andrew-m-leonard** [comment]
@karianna @gdams  we've got some people on our team looking into ways of extending the dashboard to persist and enable statistical analysis, trends etc.. Maybe using something like Grafana, Kibana, .....

**Comment by karianna** [comment]
Cool, we took a quick look at MSFT Power BI to do this as well, @gdams can report on the pros and cons for that.

**Comment by M-Davies** [comment]
@andrew-m-leonard you could probably close this now. Work is continuing on https://github.com/AdoptOpenJDK/openjdk-dashboard/issues/18
